version: '3.8'

services:
  wl-api:
    container_name: wl-api
    build:
      context: ../src
      dockerfile: Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=WlConsultingsDb;User Id=postgres;Password=postgres;
    depends_on:
      - wl-db
    networks:
      - wl-network

  wl-db:
    container_name: wl-db
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: WlConsultingsDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - wl-network

volumes:
  postgres_data:

networks:
  wl-network:
    driver: bridge